services:
  portfolioFrontend:
    image: portfoliofrontend
    container_name: portfolio_Frontend
    networks:
      reverseproxy:
        ipv4_address: 192.168.0.4
    restart: unless-stopped

networks:
  reverseproxy:
    external: true
    name: reverseproxy