services:
  portfolioBackend:
    build: .
    container_name: portfolioBackend
    restart: unless-stopped
    networks:
      reverseproxy:
        ipv4_address: 192.168.0.3
networks:
  reverseproxy:
    external: true
    name: reverseproxy